[tool.cibuildwheel]

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "mtgupf/essentia-builds:manylinux2014_x86_64"
manylinux-i686-image = "mtgupf/essentia-builds:manylinux2014_i686"

skip = ["pp*", "*-musllinux*", "*i686", "*cp36*", "*cp37*", "*cp38*"]

environment = { PROJECT_NAME="essentia", ESSENTIA_PROJECT_NAME="${PROJECT_NAME}", ESSENTIA_WHEEL_SKIP_3RDPARTY=1, ESSENTIA_WHEEL_ONLY_PYTHON=1 }

before-all = [
  "PYBIN=$(ls -1 /opt/python/cp3*-cp3*/bin/python | head -n 1)",
  "\"${PYBIN}\" waf configure --with-gaia --build-static --static-dependencies --pkg-config-path=\"${PKG_CONFIG_PATH}\"",
  "\"${PYBIN}\" waf",
  "\"${PYBIN}\" waf install"
]

test-command = "python -c 'import essentia; import essentia.standard; import essentia.streaming; from essentia.standard import MonoLoader, MetadataReader, YamlInput, Chromaprinter'"


[tool.cibuildwheel.macos]

skip = ["pp*", "*cp36*", "*cp37*", "*cp38*"]

environment = { PROJECT_NAME="essentia", ESSENTIA_PROJECT_NAME="${PROJECT_NAME}", ESSENTIA_WHEEL_SKIP_3RDPARTY=1, ESSENTIA_WHEEL_ONLY_PYTHON=1, MACOSX_DEPLOYMENT_TARGET=13.0 }

before-all = [
  "brew install pkg-config gcc readline sqlite gdbm freetype libpng",
  "brew install eigen@3 libyaml fftw ffmpeg libsamplerate libtag",
  "brew install chromaprint",
  #"brew tap MTG/essentia",
  #"brew install gaia --HEAD",
  # Override VIRTUAL_ENV set by cibuildwheel to ensure global install
  "EIGEN3_PREFIX=$(brew --prefix eigen@3) && EIGEN3_PKGCONFIG=\"${EIGEN3_PREFIX}/share/pkgconfig:${EIGEN3_PREFIX}/lib/pkgconfig\" && VIRTUAL_ENV=/usr/local python waf configure --pkg-config-path=\"${EIGEN3_PKGCONFIG}:${PKG_CONFIG_PATH}\"",
  "python waf",
  "python waf install"
]

test-command = "python -c 'import essentia; import essentia.standard; import essentia.streaming; from essentia.standard import MonoLoader, MetadataReader, YamlInput, Chromaprinter'"

[[tool.cibuildwheel.overrides]]
select = "*macosx_arm64*"

skip = ["pp*", "*cp36*", "*cp37*", "*cp38*"]

environment = { PROJECT_NAME="essentia", ESSENTIA_PROJECT_NAME="${PROJECT_NAME}", ESSENTIA_WHEEL_SKIP_3RDPARTY=1, ESSENTIA_WHEEL_ONLY_PYTHON=1, ESSENTIA_MACOSX_ARM64=1, MACOSX_DEPLOYMENT_TARGET=15.0 }

before-all = [
  "brew install pkg-config gcc readline sqlite gdbm libpng",
  "brew install eigen@3 libyaml fftw ffmpeg libsamplerate libtag",
  "brew install chromaprint",
  # Override VIRTUAL_ENV set by cibuildwheel to ensure global install
  "EIGEN3_PREFIX=$(brew --prefix eigen@3) && EIGEN3_PKGCONFIG=\"${EIGEN3_PREFIX}/share/pkgconfig:${EIGEN3_PREFIX}/lib/pkgconfig\" && VIRTUAL_ENV=/usr/local python waf configure --pkg-config-path=\"${EIGEN3_PKGCONFIG}:${PKG_CONFIG_PATH}\" --arch arm64 --no-msse",
  "python waf",
  "sudo python waf install",
]

# With Homebrew FFmpeg, delocate can bundle linked dylibs directly.
repair-wheel-command = "delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"
